routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*Dashboard*/
Route::get("/", function (){
	
	return view("auth.login");

});


Route::group(["middleware" => ["auth"]], function(){

	Route::get("/dashboard", "Admin\AdminController@dashboard")->name("dashboard");

	Route::resource("/dashboard/categories", "Admin\CategoryController");
	Route::resource("/dashboard/products", "Admin\ProductController");

	Route::get("products/pdf/", "Admin\ProductController@downloadAllPDF")->name("downpdfall");
	Route::get("product/pdf/{id}", "Admin\ProductController@downloadPDF")->name("downpdf");

	Route::resource("/dashboard/ventas/personas", "Admin\ClientController");
	Route::resource("/dashboard/ventas/ventas-clientes/", "Admin\VentaController");

	Route::resource("/dashboard/compras/personas/providers", "Admin\ProviderController");
	Route::resource("/dashboard/compras/ingresos", "Admin\IngresoController");
		Route::get("compra/pdf/{id}", "Admin\IngresoController@downloadPDF")->name("fac-compra");


	Route::resource("/dashboard/users", "Admin\UsersController");
	
	// Route::get('/home', 'HomeController@index')->name('home');

});

Auth::routes();

app/Venta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Venta extends Model
{
    protected $table="ventas";

    protected $primaryKey="idventa";


    protected $filleable = [
    	"idcliente", "tipo_voucher", "serie_voucher", "nro_voucher", "impuesto", "total_venta", "date", "status"
    ];

    protected $guarded=[

    ];
}

app/Http/Controllers/Admin/VentaController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Input;
use App\Http\Requests\VentaFormRequest;
use App\Http\Requests\IngresoRequest;

use App\Venta;
use App\Persona;

use App\DetalleVenta;
use DB;

use Carbon\Carbon;
use Response;
use Illuminate\Support\Collection;

class VentaController extends Controller{

    public function __construct()
    {
        $this->middleware("auth");
    }

    public function index(Request $request)
    {
        if($request){

            $query=trim($request->get("searchText"));//trim:elimina los espacios al comienzo y final
            $ventas=DB::table("ventas as v")
            ->join("personas as p", "v.idcliente", "=", "p.idpersona")
            ->join("detalles_ventas as dv", "v.idventa", "=", "dv.idventa")
            ->select("v.idventa", "v.fecha_hora", "p.name", "v.tipo_voucher", "v.serie_voucher", "v.nro_voucher", "v.impuesto", "v.status", "v.total_venta")
            ->where("v.nro_voucher", "LIKE", "%" . $query . "%")
            ->orWhere("v.serie_voucher", "LIKE", "%" . $query . "%")
            ->orderBy("v.idventa","desc")
            ->groupBy("v.idventa", "v.fecha_hora", "p.name", "v.tipo_voucher", "v.serie_voucher", "v.nro_voucher", "v.impuesto", "v.status")
            ->paginate(10);

            return view("dashboard.ventas.venta.index",["ventas" => $ventas, "searchText" => $query]);
        }
    }

    public function create()
    {
        $clientes=Persona::orderBy("name", "ASC")->pluck("name", "idpersona");
        // $personas=DB::table("personas")->where("tipo_cliente", "=", "Cliente")->get();
        $articulos=DB::table("products as art")
            ->join("detalle_ingresos as di", "art.idarticulo", "=", "di.idarticulo")
            ->select(DB::raw('CONCAT(art.code, " - ",art.name) AS articulo'), "art.idarticulo", "art.stok", DB::raw('avg(di.precio_venta) as precio_promedio'))
            ->where("art.status", "=", "Publicado")
            ->where("art.stok", ">", "0")
            ->groupBy("articulo", "art.idarticulo", "art.stok")
            ->get();

        // $clientes=Persona::orderBy("name", "ASC")->pluck("name", "id");
        // $persona=DB::table("personas")->where("tipo_cliente", "=", "Cliente")->get();
        // $articulos=DB::table("products as art")
        //     ->select(DB::raw('CONCAT(art.code, " - ",art.name) AS products'), "art.id")
        //     ->where("art.status", "=", "Publicado")
        //     ->get();

            return view("dashboard.ventas.venta.create", compact("clientes", "personas", "articulos"));
    }


    public function store(VentaFormRequest $request)
    {
        //Capturar exepciones en caso de error. Al momento de registrar un ingreso, se debe almacenar tambien el detalle de ingreso. Deben almacernarce ambos
        try{
            DB::beginTransaction();

            //Guardar ingreso
            $venta=new Venta();
            $venta->idcliente=$request->get("idcliente");
            $venta->tipo_voucher=$request->get("tipo_voucher");
            $venta->serie_voucher=$request->get("serie_voucher");
            $venta->nro_voucher=$request->get("nro_voucher");
            $venta->total_venta=$request->get("total_venta");

            $mytime= Carbon::now("America/Caracas");
            $venta->date=$mytime->toDateTimeString();
            $venta->impuesto="16";
            $venta->status="Entregado";

            $venta->save();

            //Guardar detalle de ingreso

            $idarticulo=$request->get("idarticulo");
            $cantidad=$request->get("cantidad");
            $descuento=$request->get("descuento");
            $precio_venta=$request->get("precio_venta");

            $cont = 0;

            while ($cont < count($idarticulo)) {

                $detalle=new DetalleVenta();
                $detalle->idventa=$venta->idventa;//Verificar id
                $detalle->idarticulo=$idarticulo[$cont];
                $detalle->cantidad=$cantidad[$cont];
                $detalle->descuento=$descuento[$cont];
                $detalle->precio_venta=$precio_venta[$cont];
                $detalle->save();

                $cont=$cont+1;        
            }   

            DB::commit();
        }
        catch(\Execption $e){
            DB::rollback();
        }

        return Redirect::to("dashboard/ventas/ventas-clientes");
    }

    public function show($id)
    {
        $venta = DB::table("ventas as v")
            ->join("personas as p", "v.idcliente", "=", "p.idpersona")
            ->join("detalles_ventas as dv", "v.idventa", "=", "dv.idventa")
            ->select("v.idventa", "v.date", "p.name", "v.tipo_voucher", "v.serie_voucher", "v.nro_voucher", "v.impuesto", "v.status", "v.total_venta")
            ->where("v.idventa", "=", $id)
            ->first();

        $detalles=DB::table("detalles_ventas as d")
            ->join("products as a", "d.idarticulo", "=", "a.idarticulo")
            ->select("a.name as articulo", "d.cantidad", "d.descuento", "d.precio_venta")
            ->where("d.idventa", "=", $id)
            ->get();    

        return view("dashboard.ventas.venta.show",compact("venta","detalles"));
    }


    public function destroy($id)
    {
        $venta=Ventas::findOrFail($id);
        $venta->status="Cancelado";
        $venta->update();

        return Redirect::to("dashboard/ventas/ventas-clientes");



        // $category = Category::find($id)->delete();

        // return back()->with("info", "La Categoría ha sido eliminada" );
    }
}

resources/views/dashboard/ventas/clientes/create.blade.php
@extends("layouts.dashboard.theme")
@section("title")
	Registrar nuevo cliente
@endsection

@section("content")
	<div class="contain-inner-section">
		<div class="page-main-header">
            <!-- Page Title -->
            <h1 class="page-name-title">Nuevo cliente</span></h1>
            <!--  Breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="{{ route("dashboard") }}">Dashboard</a></li>
                <li class="text-info">Sales</li>
                 <li><a href="{{ url("dashboard/categories") }}">Clients</a></li>
                <li class="active">New</li>
            </ol>
        </div>

    	@if(count($errors)>0)
    		@include("layouts.dashboard.message"){{--message--}}
    	@endif
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
	                <div class="section-header">
	                	<h2>Registrar cliente</h2>
	                </div>
	                <div class="section-body">
		                {!! Form::open(array("url"=>"dashboard/ventas/personas", "method"=>"POST", "autocomplete"=>"off")) !!}
		                {!! Form::token() !!}
			                @include("dashboard.ventas.clientes.partials.form-create")
		               {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

{{-- @section("scripts")
	<script src="{{ asset("assets/global/js/form_input.min.js") }}"></script>
@endsection --}}

resources/views/dashboard/ventas/clientes/disable.blade.php
@extends("layouts.dashboard.theme")
@section("title")
	Categorías inactivas
@endsection

@section("styles")
	<style type="text/css" media="screen">
		.btn1{
			width: 5rem!important;
		}
	</style>
@endsection

@section("content")
	<div class="contain-inner-section">
		  <div class="page-main-header">
            <!-- Page Title -->
            <h1 class="page-name-title">Categorías</h1>
            <!--  Breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="{{ route("dashboard") }}">Dashboard</a></li>
                <li class="text-info">Almacen</li>
                <li class="active">Categorías</li>
            </ol>
        </div>
    	@include("layouts.dashboard.message"){{--message--}}
        <div class="row">
            <div class="">
	            <div class="section-header">
	                <a href="{{ url("dashboard/categories/create") }}">
	                	<button type="button" class="btn btn-primary btn-outline float-button-light">
	                        <i class="fa fa-plus"> </i> Nueva
	                 	</button>
	                </a>
	            </div>
	            @include("dashboard.categories.partials.search")
	            <div class="section-body">
	                <div class="table-responsive">
	                   @if(count($categories->status=="Desactivada")) 
	                     <table class="table table-hover">
		                        <thead>
		                        <tr>
		                            <th>#</th>
		                            <th>Categoría</th>
		                            <th>Descripción</th>
		                            <th>Estado</th>
		                            <th>Fecha de creación</th>
		                            <th>Última actualización</th>
		                        </tr>
		                        </thead>
		                        <tbody>
		                        @foreach($categories as $category)
			                        <tr class="text-capitalize">
			                            <th scope="row">
			                                        	{{ $category->id }}
			                            </th>
			                            <td>{{ $category->name }}
			                             <br>
			                             <br>
			                             <a href="{{ route("categories.show" , $category->id) }}">
			                               <button type="button" class="btn1 btn btn-primary btn-outline btn-xs float-button-light">
			                                    <span class="fa fa-eye"> Ver</span>
			                               </button>
			                             </a>
			                             <a href="{{ route("categories.edit" , $category->id) }}">
			                               <button type="button" class="btn1 btn btn-success btn-outline btn-xs float-button-light">
			                                    <span class="fa fa-exchange"></span> Modificar
			                               </button>
			                             </a>
			                             <a href="#">
			                              <button type="button" data-target="#modal-delete-{{ $category->id }}" data-toggle="modal" class="btn1 btn btn-danger btn-outline btn-xs float-button-light">
			                               		<span class="fa fa-trash"></span> Eliminar
			                              </button>
			                             </a>
			                            </td>
			                            <td>
			                            	@if($category->description)
			                            		{{ $category->description }}
			                            	@else
			                            		N/D
			                            	@endif
			                            </td>
			                            <td>{{ $category->status }}</td>
			                            <td>{{ $category->created_at }}</td>
			                            <td>{{ $category->updated_at }}</td>
			                        </tr>
			                        @include("dashboard.categories.partials.modal_delete")
		                        @endforeach
		                        </tbody>
		                    </table>
	                    @else
	                        No hay categorías  
	                       	<a href="{{ url("dashboard/categories") }}">
		                       	 <button type="button" class="btn1 btn btn-info btn-outline btn-xs float-button-light" data-target="#danger-modal" data-toggle="modal">
				                    <span class="fa fa-arrow-left"></span> Regresar
				                </button>
	                       </a>
	                    @endif
	                </div>
	                {{ $categories->render() }}
	            </div>
	        </div>
        </div>
    </div>
@endsection

@section("scripts")
	<script src="{{ asset("assets/global/js/form_input.min.js") }}"></script>
@endsection

resources/views/dashboard/ventas/clientes/edit.blade.php
@extends("layouts.dashboard.theme")
@section("title")
	Edición de cliente
@endsection

@section("styles")
	<style type="text/css">
		#textarea-cat{
			height: 10rem;
			max-width: 31.5rem;
			max-height: 31.5rem;
		}
	</style>
@endsection

@section("content")
	<div class="contain-inner-section">
		<div class="page-main-header">
            <!-- Page Title -->
            <h1 class="page-name-title">Editar datos del cliente</span></h1>
            <!--  Breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="{{ route("dashboard") }}">Dashboard</a></li>
                <li class="text-info">Sales</li>
                 <li><a href="{{ url("dashboard/categories") }}">Clients</a></li>
                <li class="active">Edit</li>
            </ol>
        </div>

    	@if(count($errors)>0)
    		@include("layouts.dashboard.message"){{--message--}}
    	@endif
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
	                <div class="section-header">
	                	<h2>Editar datos del cliente</h2>
	                </div>
	                <div class="section-body">
		                {!! Form::model($persona,["method" => "PATCH", "route" => ["personas.update", $persona->idpersona]]) !!}
		                {!! Form::token() !!}
			                @include("dashboard.ventas.clientes.partials.form-edit")
		               {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/ventas/clientes/index.blade.php
@extends("layouts.dashboard.theme")
@section("title")
	Clientes
@endsection

@section("styles")
	<style type="text/css" media="screen">
		.btn1{
			width: 6rem!important;
		}
	</style>
@endsection

@section("content")
	<div class="contain-inner-section">
		  <div class="page-main-header">
            <!-- Page Title -->
            <h1 class="page-name-title">Clientes</h1>
            <!--  Breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="{{ route("dashboard") }}">Dashboard</a></li>
                 <li class="text-info">Ventas</li>
                <li class="active">Clientes</li>
            </ol>
        </div>
    	@include("layouts.dashboard.message"){{--message--}}
        <div class="row">
            <div class="">
	            <div class="section-header">
	                <a href="{{ url("dashboard/ventas/personas/create") }}">
	                	<button type="button" class="btn btn-primary btn-outline float-button-light">
	                        <i class="fa fa-plus"> </i> Nuevo
	                 	</button>
	                </a>
	            </div>
	            @include("dashboard.ventas.clientes.partials.search")
	            <div class="section-body">
	                <div class="table-responsive">
	                   @if(count($personas)) 
	                     <table class="table table-hover">
		                        <thead>
		                        <tr>
		                            <th>#</th>
		                            <th>Nombre</th>
		                            <th>Email</th>
		                            <th>Tipo de documento</th>
		                            <th>Nro de Documento</th>
		                            <th>Registrado el</th>
		                            <th>Última actualización</th>
		                        </tr>
		                        </thead>
		                        <tbody>
		                        @foreach($personas as $persona)
			                        <tr class="text-capitalize">
			                            <th scope="row">
			                            {{ $persona->idpersona }}
			                            </th>
			                            <td>{{ $persona->name }}
			                             <br>
			                             <br>
			                             <a href="{{ route("personas.show" , $persona->idpersona) }}">
			                               <button type="button" class="btn1 btn btn-primary btn-outline btn-xs float-button-light">
			                                    <span class="fa fa-eye"> Ver</span>
			                               </button>
			                             </a>
			                             <a href="{{ route("personas.edit" , $persona->idpersona) }}">
			                               <button type="button" class="btn1 btn btn-success btn-outline btn-xs float-button-light">
			                                    <span class="fa fa-exchange"></span> Modificar
			                               </button>
			                             </a>
			                             <a href="#">
			                              <button type="button" data-target="#modal-delete-{{ $persona->idpersona }}" data-toggle="modal" class="btn1 btn btn-danger btn-outline btn-xs float-button-light">
			                               		<span class="fa fa-trash"></span> Eliminar
			                              </button>
			                             </a>
			                            </td>
			                            <td>
			                            	{{ $persona->email }}
			                            </td>
			                            <td>{{ $persona->document }}</td>
			                            <td>{{ $persona->nro_document }}</td>
			                          {{--   <td>{{ $persona->phone }}</td>
			                            <td>{{ $persona->address }}</td> --}}
			                            <td>{{ $persona->created_at }}</td>
			                            <td>{{ $persona->updated_at }}</td>
			                        </tr>
			                        @include("dashboard.ventas.clientes.partials.modal_delete")
		                        @endforeach
		                        </tbody>
		                    </table>
	                    @else
	                        No hay clientes registrados  
	                       	@if($searchText)
	                       		<a href="{{ url("dashboard/ventas/personas") }}">
			                       	 <button type="button" class="btn1 btn btn-info btn-outline btn-xs float-button-light" data-target="#danger-modal" data-toggle="modal">
					                    <span class="fa fa-arrow-left"></span> Regresar
					                </button>
	                       		</a>
	                       	@endif
	                    @endif
	                </div>
	                {{ $personas->render() }}
	            </div>
	        </div>
        </div>
    </div>
@endsection

{{-- @section("scripts")
	<script src="{{ asset("assets/global/js/form_input.min.js") }}"></script>
@endsection --}}

resources/views/dashboard/ventas/clientes/show.blade.php
@extends("layouts.dashboard.theme")
@section("title")
	Cliente: {{ $persona->name }}
@endsection

@section("styles")
	<style type="text/css">
		#textarea-cat{
			height: 10rem;
			max-width: 31.5rem;
			max-height: 31.5rem;
		}
	</style>
@endsection

@section("content")
	<div class="contain-inner-section">
		<div class="page-main-header">
            <!-- Page Title -->
            <h1 class="page-name-title">Cliente {{ $persona->name }}</span></h1>
            <!--  Breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="{{ route("dashboard") }}">Dashboard</a></li>
                <li class="text-info">Almacen</li>
                 <li><a href="{{ url("dashboard/ventas/personas/") }}">Clients</a></li>
                <li class="active">Show</li>
            </ol>
        </div>

    	@if(count($errors)>0)
    		@include("layouts.dashboard.message"){{--message--}}
    	@endif
        <div class="row">
        	 	<div class="section-header">
	                <a href="{{ url("dashboard/ventas/personas/") }}">
	                	<button type="button" class="btn btn-warning btn-outline float-button-light">
	                        <i class="fa fa-arrow-left"> </i> Volver
	                 	</button>
	                </a>
	            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 section-body">
	              
	                 <div class="">
                    
                    <div class="row">
                        <div class="col-md-8">
                            <div class="profile-left-section">
                                <ul class="nav nav-pills">
                                    <li class="active"><a data-toggle="tab" href="#info" class="float-button-light">Información del Cliente</a>
                                    </li>
                                   
                                </ul>
                                <div class="tab-content">
                                    <div id="info" class="tab-pane fade in active">
                                        <div class="section-body">
                                            <div class="profile-body">
                                           
                                            <div class="row">
                                                <div class="prosonal-info">
                                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                    <p><span>Nombre del Cliente:- </span> {{ $persona->name}}</p>
                                                    <p><span>Tipo de documento </span> {{ $persona->document }} </p>
                                                    <p><span>Nro. de Documento </span> {{ $persona->nro_document }} </p> 
                                                    <p><span>Email:- </span> {{ $persona->email}}</p>
                                                    <p><span>Teléfono:- </span> {{ $persona->phone }}</p>

                                                </div>
                                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                    
                                                    <p><span>Agregado al sistema :- </span> {{ $persona->created_at}}</p>
                                                    <p><span>Última actualización:- </span> {{ $persona->updated_at}}</p>
                                                    <p><span>Dirección:- </span> {{ $persona->address }}</p>
                                                   
                                                </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                       
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section("scripts")
	<script src="{{ asset("assets/global/js/form_input.min.js") }}"></script>
@endsection